function createfigure(zdata1, zdata2, zdata3, YMatrix1)
%CREATEFIGURE(ZDATA1,ZDATA2,ZDATA3,YMATRIX1)
%  ZDATA1:  surface zdata
%  ZDATA2:  surface zdata
%  ZDATA3:  surface zdata
%  YMATRIX1:  matrix of y data

YMatrix1
%  Auto-generated by MATLAB on 15-Jan-2015 17:16:54

% Create figure
figure1 = figure('XVisual',...
    '0x97 (TrueColor, depth 24, RGB mask 0xff0000 0xff00 0x00ff)');

% Create axes
axes1 = axes('Parent',figure1,'OuterPosition',[0 0.5 1 0.5]);
view(axes1,[-37.5 30]);
grid(axes1,'on');
hold(axes1,'all');

% Create surf
surf(zdata1,'Parent',axes1);

% Create surf
surf(zdata2,'Parent',axes1);

% Create surf
surf(zdata3,'Parent',axes1);

% Create axes
axes2 = axes('Parent',figure1,'OuterPosition',[0 0 1 0.5]);
% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes2,[0 60]);
% Uncomment the following line to preserve the Y-limits of the axes
ylim(axes2,[-2.5905203908e-18 1.1]);
box(axes2,'on');
hold(axes2,'all');

% Create multiple lines using matrix input to plot
plot1 = plot(YMatrix1,'Parent',axes2);
set(plot1(1),'DisplayName','\Xi_{[e1, e2]}');
set(plot1(2),'DisplayName','\Xi_{[e1, e2, e1, e2]}');
set(plot1(3),'DisplayName','\Xi_{[e1, e2, e1, e2, -e1, e2]}');

% Create legend
legend(axes2,'show');

